# NumPy

In [1]:
a = [1,2,3,4]
b = [2,3,4,5]

ab = []                        

for i in range(0, len(a)):
  ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [2]:
import numpy as np 

a = np.array([1,2,3,4])

b = np.array([2,3,4,5])

a * b

array([ 2,  6, 12, 20])

In [4]:
L = [1,2,"a",1.2]
L

[1, 2, 'a', 1.2]

In [5]:
[type(i) for i in L]

[int, int, str, float]

# Creating NumPy Arrays

## Creating Arrays from Lists

In [6]:
import numpy as np 

np.array([12,33,4,5])

a = np.array([12,33,4,5])

a

type(a)

numpy.ndarray

In [7]:
np.array([3.14, 4,6,1.2])

array([3.14, 4.  , 6.  , 1.2 ])

In [8]:
np.array([3.14, 4,6,1.2], dtype = 'float32')

array([3.14, 4.  , 6.  , 1.2 ], dtype=float32)

In [9]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.full((2,3), 9)

array([[9, 9, 9],
       [9, 9, 9]])

In [12]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [13]:
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [14]:
np.random.normal(0,1, (3,4))

array([[-2.28526245,  0.04451301,  0.80678405,  0.51850538],
       [ 0.1111659 ,  1.1659265 ,  0.92711403, -0.67991633],
       [ 0.95883935, -0.30322989,  0.50296108, -2.26825377]])

In [15]:
np.random.randint(0,10, (2,2))

array([[6, 1],
       [7, 3]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Numpy Formatting

* **ndim**: number of dimensions

* **shape**: size information

* **size**: total number of elements

* **dtype**: array data type

In [17]:
import numpy as np
a = np.random.randint(10, size = 10)
a.ndim
a.shape
a.size
a.dtype

dtype('int32')

In [18]:
a = np.random.randint(10, size = (10, 5))
a

array([[1, 1, 1, 9, 6],
       [3, 7, 5, 4, 0],
       [7, 3, 8, 8, 0],
       [3, 4, 6, 1, 0],
       [2, 9, 0, 3, 1],
       [2, 2, 2, 1, 9],
       [7, 4, 3, 3, 5],
       [8, 3, 5, 8, 3],
       [1, 1, 9, 4, 1],
       [6, 0, 9, 2, 1]])

In [19]:
a.ndim

2

In [20]:
a.shape

(10, 5)

In [21]:
a.size

50

In [22]:
a.dtype

dtype('int32')

In [23]:
a = np.random.randint(10, size = (3,5,2))
a

array([[[5, 4],
        [1, 9],
        [0, 6],
        [4, 6],
        [7, 1]],

       [[1, 2],
        [6, 8],
        [0, 7],
        [3, 2],
        [7, 7]],

       [[6, 1],
        [9, 2],
        [4, 2],
        [6, 0],
        [6, 1]]])

In [24]:
a.ndim

3

In [25]:
a.shape

(3, 5, 2)

In [26]:
a.size

30

In [27]:
a.dtype

dtype('int32')

In [28]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
a = np.array([1,2,3])

In [31]:
a

array([1, 2, 3])

In [32]:
b = a.reshape((1,3))

In [33]:
b.ndim

2

In [34]:
a

array([1, 2, 3])

In [36]:
a[np.newaxis, :] # Add a new axis using np.newaxis

array([[1, 2, 3]])

In [38]:
a[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [ ]:
#one dimensional

In [39]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [40]:
x

array([1, 2, 3])

In [41]:
y

array([4, 5, 6])

In [42]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [43]:
z = [1,2,3]

In [44]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [ ]:
# 2 dimensional

In [45]:
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [47]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
# different dimensions 

In [48]:
a = np.array([1, 2, 3])

b = np.array([[9, 8, 7], 
              [6, 5, 4]])

In [49]:
a

array([1, 2, 3])

In [50]:
b

array([[9, 8, 7],
       [6, 5, 4]])

In [51]:
np.vstack([a,b])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [52]:
a = np.array([[99],
              [99]])

In [53]:
a

array([[99],
       [99]])

In [54]:
np.hstack([a,b])

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

In [ ]:
#array splitting

In [55]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x

[1, 2, 3, 99, 99, 3, 2, 1]

In [56]:
np.split(x, [3,5]) #  function to split the list x into multiple subarrays based on the specified indices.

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [57]:
a,b,c = np.split(x, [3,5])

In [58]:
a

array([1, 2, 3])

In [59]:
b

array([99, 99])

In [60]:
c

array([3, 2, 1])

In [61]:
m = np.arange(16).reshape((4, 4))

In [62]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [63]:
lower, upper = np.vsplit(m, [2])

In [64]:
upper

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
lower

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [66]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [67]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
left, right = np.hsplit(m, [2])

In [72]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [73]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [ ]:
#array sorting

In [74]:
v = np.array([2, 1, 4, 3, 5])
v

array([2, 1, 4, 3, 5])

In [75]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [ ]:
v

In [76]:
v.sort()

In [77]:
v

array([1, 2, 3, 4, 5])

In [78]:
v = np.array([2, 1, 4, 3, 5])

In [79]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [80]:
i = np.argsort(v) # it gives the indices that would rearrange the elements of v in ascending order

In [81]:
i

array([1, 0, 3, 2, 4], dtype=int64)

In [82]:
v

array([2, 1, 4, 3, 5])

In [83]:
v[i]

array([1, 2, 3, 4, 5])

# NumPy Operations

## Accessing values by Index

In [84]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([4, 8, 5, 7, 7, 2, 6, 4, 9, 9])

In [85]:
a[0]

4

In [86]:
a[-2]

9

In [87]:
a[0] = 1

In [88]:
a

array([1, 8, 5, 7, 7, 2, 6, 4, 9, 9])

In [89]:
a = np.random.randint(10, size = (3, 5))
a

array([[0, 2, 7, 1, 1],
       [0, 2, 2, 5, 0],
       [1, 4, 8, 5, 4]])

In [90]:
a[0,0]

0

In [91]:
a[1,1]

2

In [92]:
a[0,0] = 1

In [93]:
a[0,0]

1

In [94]:
a[0,0] = 2.2

In [95]:
a[0,0]

2

## Accessing an Array Subset by Slicing

In [4]:
import numpy as np
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
a[0:3]

array([20, 21, 22])

In [6]:
a[:3]

array([20, 21, 22])

In [7]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [8]:
a[::2]

array([20, 22, 24, 26, 28])

In [9]:
a[1::2]

array([21, 23, 25, 27, 29])

In [10]:
a[2::2]

array([22, 24, 26, 28])

In [11]:
a[1::3]

array([21, 24, 27])

In [13]:
a = np.random.randint(10, size = (5, 5))
a

array([[0, 7, 1, 6, 8],
       [2, 2, 5, 2, 1],
       [0, 7, 1, 4, 7],
       [2, 1, 2, 2, 5],
       [0, 0, 2, 0, 3]])

In [14]:
a[:,0]

array([0, 2, 0, 2, 0])

In [15]:
a[:,1]

array([7, 2, 7, 1, 0])

In [16]:
a[:,4]

array([8, 1, 7, 5, 3])

In [17]:
a

array([[0, 7, 1, 6, 8],
       [2, 2, 5, 2, 1],
       [0, 7, 1, 4, 7],
       [2, 1, 2, 2, 5],
       [0, 0, 2, 0, 3]])

In [18]:
a[4,:]

array([0, 0, 2, 0, 3])

In [19]:
a[0]

array([0, 7, 1, 6, 8])

In [20]:
a[:2,:3]

array([[0, 7, 1],
       [2, 2, 5]])

In [21]:
a[0:2,0:3]

array([[0, 7, 1],
       [2, 2, 5]])

In [22]:
a[::,:2]

array([[0, 7],
       [2, 2],
       [0, 7],
       [2, 1],
       [0, 0]])

In [23]:
a[:,:2]

array([[0, 7],
       [2, 2],
       [0, 7],
       [2, 1],
       [0, 0]])

In [24]:
a[1:3,0:2]

array([[2, 2],
       [0, 7]])

In [26]:
a = np.random.randint(10, size = (5, 5))
a

array([[8, 6, 9, 7, 4],
       [8, 5, 3, 0, 6],
       [7, 2, 6, 5, 8],
       [8, 3, 4, 9, 8],
       [6, 8, 1, 2, 1]])

In [27]:
sub_a = a[0:3,0:2]

In [28]:
sub_a

array([[8, 6],
       [8, 5],
       [7, 2]])

In [30]:
sub_a[0,0] = 9999
sub_a[1,1] = 9999

In [31]:
sub_a

array([[9999,    6],
       [   8, 9999],
       [   7,    2]])

In [32]:
a

array([[9999,    6,    9,    7,    4],
       [   8, 9999,    3,    0,    6],
       [   7,    2,    6,    5,    8],
       [   8,    3,    4,    9,    8],
       [   6,    8,    1,    2,    1]])

In [33]:
sub_b = a[0:3,0:2].copy()

In [34]:
sub_b

array([[9999,    6],
       [   8, 9999],
       [   7,    2]])

In [35]:
sub_b[0,0] = 9999
sub_b[1,1] = 9999

In [36]:
a

array([[9999,    6,    9,    7,    4],
       [   8, 9999,    3,    0,    6],
       [   7,    2,    6,    5,    8],
       [   8,    3,    4,    9,    8],
       [   6,    8,    1,    2,    1]])

## Operations by Fancy Index 

In [37]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [39]:
v[1]
v[3]

9

In [40]:
[v[1], v[3]]

[3, 9]

In [41]:
arg_1 = [1,3,5]

In [42]:
v[arg_1]

array([ 3,  9, 15])

In [43]:
m = np.arange(9).reshape((3, 3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
row = np.array([0,1])
column = np.array([1,2])

In [47]:
m[row, column]

array([1, 5])

In [48]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
m[0, [1,2]]

array([1, 2])

In [50]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [51]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
index = np.array([0,1,2])
index

array([0, 1, 2])

In [53]:
v[index] = 99

In [54]:
v

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9])

In [55]:
v[[0,1]] = [4,6]

In [56]:
v

array([ 4,  6, 99,  3,  4,  5,  6,  7,  8,  9])

# Conditional Operations

In [57]:
v = np.array([1,2,3,4,5])

In [58]:
v > 3

array([False, False, False,  True,  True])

In [59]:
v < 3

array([ True,  True, False, False, False])

In [60]:
v <= 3

array([ True,  True,  True, False, False])

In [61]:
v == 3

array([False, False,  True, False, False])

In [62]:
v != 3

array([ True,  True, False,  True,  True])

In [63]:
(2 * v)

array([ 2,  4,  6,  8, 10])

In [64]:
(v ** 2)

array([ 1,  4,  9, 16, 25])

In [65]:
(2 * v) == (v ** 2)

array([False,  True, False, False, False])

In [ ]:
#ufunc

np.equal
np.not_equal
np.less
np.less_equal
np.greater
np.greater_equal

In [66]:
v = np.array([1,2,3,4,5])

In [67]:
np.equal(3,v)

array([False, False,  True, False, False])

In [68]:
np.equal([0,1,3], np.arange(3))

array([ True,  True, False])

In [69]:
np.arange(3)

array([0, 1, 2])

In [70]:
v = np.random.randint(0, 10, (3, 3))
v

array([[6, 9, 1],
       [5, 9, 6],
       [4, 1, 3]])

In [71]:
v > 5

array([[ True,  True, False],
       [False,  True,  True],
       [False, False, False]])

In [72]:
np.sum(v > 5)

4

In [73]:
np.sum((v > 3) & (v < 7))

4

In [74]:
(v > 3) & (v < 7)

array([[ True, False, False],
       [ True, False,  True],
       [ True, False, False]])

In [75]:
np.sum((v > 3) | (v < 7))

9

In [76]:
np.sum(v > 4, axis = 1)

array([2, 3, 0])

In [77]:
np.sum(v > 4, axis = 0)

array([2, 2, 1])

In [78]:
np.all(v > 4)

False

In [79]:
np.all(v > 0)

True

In [81]:
np.any(v > 4)

True

In [82]:
np.all(v > 4, axis = 0)

array([False, False, False])

In [83]:
np.all(v > 4, axis = 1)

array([False,  True, False])

In [84]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [85]:
v[0]

1

In [86]:
v > 3

array([False, False, False,  True,  True])

In [87]:
v[(v > 1) & (v < 5)]

array([2, 3, 4])

# NumPy Mathematiocal Operations

In [88]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [89]:
a - 1

array([-1,  0,  1,  2,  3])

In [90]:
a / 2

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
a * 5 

In [ ]:
a ** 2

In [ ]:
a % 2

In [ ]:
5*(a/2*9)

In [ ]:
a

In [ ]:
np.add(a,2)

In [ ]:
np.subtract(a,1)

In [ ]:
np.multiply(a,3)

In [ ]:
np.divide(a,3)

In [ ]:
np.power(a,3)

In [91]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [92]:
np.add.reduce(a) # sum

15

In [93]:
np.add.accumulate(a)

array([ 1,  3,  6, 10, 15])

In [94]:
a = np.random.normal(0, 1, 30)
a

array([ 0.40066473, -1.80340567,  0.05155414, -1.41992986, -0.08844409,
        0.03498593,  0.75570958, -0.88538936, -0.81809793,  0.69991975,
       -0.20953402, -0.02274134,  0.23041277,  0.30879301, -1.33913502,
        1.75954794,  2.5943923 , -1.01135226,  0.00781862,  0.54641839,
       -2.30054508, -0.01798005,  1.40427889, -0.610212  , -1.81865918,
       -1.09099732, -0.78540431,  0.2436287 ,  0.81498805, -1.18243257])

In [95]:
np.mean(a)

-0.18503824273647726

In [ ]:
np.std(a)

In [ ]:
np.var(a)

In [ ]:
np.median(a)

In [ ]:
sum(a)

np.nanmean(a)

np.nanstd(a)

np.nanvar(a)

np.nanargmin(a) 

np.nanargmax(a) 

np.nanmedian(a)

In [96]:
np.min(a)

-2.3005450830085703

In [97]:
np.max(a)

2.5943923023013635

In [98]:
a = np.random.normal(0, 1, (3,3))
a

array([[ 0.67388363, -0.0333864 , -1.66239071],
       [-0.07533468,  0.06653053,  0.17576995],
       [ 1.61431621,  0.67835647,  0.16643404]])

In [ ]:
a.sum()

In [99]:
a.sum(axis = 1)

array([-1.02189348,  0.1669658 ,  2.45910673])

# Working with Arrays of Different Sizes (broadcasting)

In [100]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

a + b

array([2, 4, 6])

In [101]:
m = np.ones((3, 3))
m

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [102]:
a

array([1, 2, 3])

In [103]:
a + m

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [104]:
a = np.arange(3)
a

array([0, 1, 2])

In [105]:
b = np.arange(3)[:, np.newaxis]
b

array([[0],
       [1],
       [2]])

In [106]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [107]:
M = np.ones((2, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.]])

In [108]:
a = np.arange(3)
a

array([0, 1, 2])

In [109]:
a + M

array([[1., 2., 3.],
       [1., 2., 3.]])

In [110]:
a = np.arange(3).reshape((3, 1))
a

array([[0],
       [1],
       [2]])

In [111]:
b = np.arange(3)
b

array([0, 1, 2])

In [113]:
a.shape

(3, 1)

In [112]:
b.shape

(3,)

In [114]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [115]:
m = np.ones((3,2))
m

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [116]:
a = np.arange(3)
a

array([0, 1, 2])

In [117]:
m.shape

(3, 2)

In [118]:
a.shape

(3,)

In [119]:
a + m

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

# Numpy Structured Arrays

## Hello! Good Bye! Numpy

In [120]:
name = ['Andreas', 'Ludwig', 'Melina']
age = [25, 22, 19]
height = [168, 159, 172]

In [121]:
data = np.zeros(3, dtype={'names':('name', 'age', 'height'),
                          'formats':('U10', 'i4', 'f8')})

In [122]:
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('height', '<f8')])

In [123]:
data['name'] = name
data['age'] = age
data['height'] = height

In [124]:
data

array([('Andreas', 25, 168.), ('Ludwig', 22, 159.), ('Melina', 19, 172.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('height', '<f8')])

In [126]:
data['name']

array(['Andreas', 'Ludwig', 'Melina'], dtype='<U10')

In [127]:
data[0]

('Andreas', 25, 168.)

In [ ]:
data[data['age'] < 25]['name']

# Pandas

## Pandas Series

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
pd.Series([1,2,3,4])

In [ ]:
seri = pd.Series([1,2,3,4])

In [ ]:
type(seri)

In [ ]:
seri.axes

In [ ]:
seri.dtype

In [ ]:
seri.empty

In [ ]:
seri.ndim

In [ ]:
seri.size

In [ ]:
seri.values

In [ ]:
seri.head(2)

In [ ]:
seri[0:3]

In [ ]:
seri.tail(2)

In [ ]:
a = np.array([1,2,3,566,88])
a

In [ ]:
type(a)

In [ ]:
seri = pd.Series(a)

In [ ]:
seri

In [ ]:
seri.index

In [ ]:
seri[0]

In [ ]:
pd.Series([1,5,0.9,34], index = [1,3,5,7])

In [ ]:
seri = pd.Series([1,5,0.9,34], index = ['a','b','c','d'])

In [ ]:
seri["a"]

In [ ]:
sozluk = { "reg" : 10, "loj" : 11, "cart" : 12}

In [ ]:
sozluk

In [ ]:
seri = pd.Series(sozluk)

In [ ]:
seri["reg"]

In [ ]:
seri["loj":"cart"]

In [ ]:
seri

In [ ]:
pd.concat([seri, seri])

In [ ]:
seri.append(seri)

In [ ]:
seri

## Serilerde Eleman İşlemleri

In [ ]:
a = np.array([1, 2, 3,33,55,66])
seri = pd.Series(a)
seri

In [ ]:
seri[0]

In [ ]:
seri[0:3]

In [ ]:
seri = pd.Series([121, 200, 150, 99], 
                 index=["reg", "loj", "cart", "rf"])
seri

In [ ]:
seri.index

In [ ]:
seri.keys

In [ ]:
list(seri.items())

In [ ]:
seri.values

In [ ]:
seri

In [ ]:
"reg" in seri

In [ ]:
seri["reg"]

In [ ]:
seri[['rf', 'reg']]

In [ ]:
seri["rf"] = 125

In [ ]:
seri

In [ ]:
seri['loj': 'rf']

In [ ]:
seri[0:2]

In [ ]:
seri = pd.Series([121, 200, 150, 99], index=["reg", "loj", "cart", "rf"])
seri

In [ ]:
seri[(seri > 125) & (seri < 200)]

In [ ]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

In [ ]:
data[0]

In [ ]:
data[1]

In [ ]:
data[1:3]

In [ ]:
data[0:3]

In [ ]:
# loc label based indexing, tanımlandığı şekli ile index yakalamak

In [ ]:
data

In [ ]:
data.loc[0:5]

In [ ]:
# iloc positional indexing, indexi sıfırlayarak yakalamak

In [ ]:
data

In [ ]:
data.iloc[2]

In [ ]:
data.iloc[0:3]